// ? To be reconsidered, given the large number
// ? of records it'll have and the large size in
// ? memory
// ?* will take much less memory if used properly

const { DataTypes } = require('sequelize');

// * by default, should only create an attendance
// * record for every student in in every section for
// * every period/session

module.exports = function(sequelize) {
  const Attendance = sequelize.define('attendance', {
    //? ID Field is omitted here but i think it is being
    //? Automatically generated by sequelize or sqlite


    // * reference to a section (associations)

    // * reference to a student in that section (associations)


    // date of the period/session
    date: DataTypes.DATE,

    // wether the student has attended or not
    attended: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    }
  });

  return Attendance;
};
